#+TITLE: Changes
* 2021-07-10
Adding a configuration and a command for defining and quickly visiting a "home" for a collection.

** New command
*** =org-collection-visit-home=
Goto the home of a collection, if it exist.

** New property for configuration
*** :home
Next to the already existing :name, :require and :customization, one can now also declare :home. It can take a string with a filename within the collection.

Example:
#+begin_src emacs-lisp
  ; -*- mode: emacs-lisp -*-
  (org-collection-definition
   :name "Personal"
   :home "start here.org"
   :require (org-agenda)
   :customization (;; Agenda
                   (org-agenda-files (":path:"))))
#+end_src

** Keyboard shortcut additions
- ~C-c z h~ (=org-collection-visit-home=)

* 2021-05-15 (Version 0.2)
This software probably isn't used anywhere yet so no care is taken for
backwards compatability.

With the change today, some incompatabilities in user facing functions were added though. Notably the following:

Rename of:
- =org-collection-lock= to =org-collection-load=
- =org-collection-unlock= to =org-collection-unload=

Some new commands are added and some keyboard shortcuts are added.

** New commands
*** =org-collection-create=
Helper that will create and register a new location. Default template hardcoded.

*** =org-collection-visit-settings=
Helper that will take you to the settings-file of a collection of choice.

** Keyboard shortcut additions
- ~C-c z c~ (=org-collection-create=)
- ~C-c z s~ (=org-collection-visit-settings=)
- ~C-c z f~ (=org-collection-visit-file=)
